version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/photo_studio_erp?schema=public
      - JWT_SECRET=your-secret-key
      - PORT=3001
      - CORS_ORIGINS=http://localhost:3000,http://192.168.168.114:3000,http://fw.itlaf.com.br:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=photo_studio_erp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 